### ISSUE TITLE
govendor sync causes build errors

### ISSUE THREAD

**Issue by thedrow** [tus/tusd#158]
When I typed govendor sync I got the following errors:

```
# github.com/tus/tusd/vendor/google.golang.org/grpc
vendor/google.golang.org/grpc/call.go:82: stream.StatusCode undefined (type *transport.Stream has no field or method StatusCode)
vendor/google.golang.org/grpc/call.go:284: stream.StatusCode undefined (type *transport.Stream has no field or method StatusCode)
vendor/google.golang.org/grpc/call.go:284: stream.StatusDesc undefined (type *transport.Stream has no field or method StatusDesc)
vendor/google.golang.org/grpc/server.go:648: too many arguments in call to t.WriteStatus
	have (*transport.Stream, codes.Code, string)
	want (*transport.Stream, *"github.com/tus/tusd/vendor/google.golang.org/grpc/status".Status)
vendor/google.golang.org/grpc/server.go:654: too many arguments in call to t.WriteStatus
	have (*transport.Stream, codes.Code, string)
	want (*transport.Stream, *"github.com/tus/tusd/vendor/google.golang.org/grpc/status".Status)
vendor/google.golang.org/grpc/server.go:666: too many arguments in call to t.WriteStatus
	have (*transport.Stream, codes.Code, string)
	want (*transport.Stream, *"github.com/tus/tusd/vendor/google.golang.org/grpc/status".Status)
vendor/google.golang.org/grpc/server.go:671: too many arguments in call to t.WriteStatus
	have (*transport.Stream, codes.Code, string)
	want (*transport.Stream, *"github.com/tus/tusd/vendor/google.golang.org/grpc/status".Status)
vendor/google.golang.org/grpc/server.go:693: too many arguments in call to t.WriteStatus
	have (*transport.Stream, codes.Code, string)
	want (*transport.Stream, *"github.com/tus/tusd/vendor/google.golang.org/grpc/status".Status)
vendor/google.golang.org/grpc/server.go:732: too many arguments in call to t.WriteStatus
	have (*transport.Stream, codes.Code, string)
	want (*transport.Stream, *"github.com/tus/tusd/vendor/google.golang.org/grpc/status".Status)
vendor/google.golang.org/grpc/server.go:760: too many arguments in call to t.WriteStatus
	have (*transport.Stream, codes.Code, string)
	want (*transport.Stream, *"github.com/tus/tusd/vendor/google.golang.org/grpc/status".Status)
vendor/google.golang.org/grpc/server.go:760: too many errors
```

This means that the commit pointer to grpc is incorrect somehow.

**Comment by Acconut** [comment]
I just tested it by myself and cannot reproduce your issue (go1.8 and govendor 1.0.9). The `govendor sync` command completes without errors. What does your environment look like? Did you make modifications to the vendor/ directory?

**Comment by thedrow** [comment]
`govendor sync` completes without errors.
It's the compilation that fails.

**Comment by thedrow** [comment]
This is what I'm getting (only on Linux): https://ci.appveyor.com/project/Acconut/tusd/build/1.0.511#L49

**Comment by Acconut** [comment]
Ok, now I get what you mean. This may be caused by #106 but I don't know for sure. Anyway, I just updated all dependencies (using `govendor fetch +vendor`) and they are all on their latest versions, which corrected the build error. So, if you pull from master right now, you should have no issues.

**Comment by thedrow** [comment]
I'll give it a try when I get home

**Comment by Acconut** [comment]
Closing this issue due to inactivity. Feel free to leave a comment if you want to continue the discussion :)
