### ISSUE TITLE
Golang HTTP uploading file to S3 using tusd only uploading .info (metadata)

### ISSUE THREAD

**Issue by arck123** [tus/tusd#326]
**Question**
I am using the tusd library to upload a file directly to S3 in Go. It seems to be functioning however tusd uploads two files a .info metadata file and a .bin actual content file. only uploading metadata in storage S3. why only upload .info and .bin nothing ?

**Setup details**
"github.com/tus/tusd"
"github.com/tus/tusd/filestore"
"github.com/aws/aws-sdk-go/aws"
"github.com/aws/aws-sdk-go/aws/credentials"
"github.com/aws/aws-sdk-go/aws/session"
"github.com/aws/aws-sdk-go/service/s3"
"github.com/tus/tusd/s3store"

target := config.MediaServerPathS3 + "/tus"
	lib.CleanUp(target)
	gocron.Every(30).Minutes().Do(lib.CleanUp, target)
	go gocron.Start()
	composer := tusd.NewStoreComposer()
	store := filestore.FileStore{
		Path: config.MediaServerPathS3 + "/tus",
	}
	s3Config := &aws.Config{
		Credentials:      credentials.NewStaticCredentials(config.AccessKeyID, config.SecretAccessKey, ""),
		Endpoint:         aws.String(config.Endpoint),
		Region:           aws.String(config.Location),
		DisableSSL:       aws.Bool(true),
		S3ForcePathStyle: aws.Bool(true),
	}
	ml := s3store.New(config.BucketName, s3.New(session.Must(session.NewSession()), s3Config))
	var finisherDataStore tusd.FinisherDataStore = controllers.FinisherDataStore{
		Store: store,
	}
	composer.UseFinisher(finisherDataStore)
	log.Println(composer.Capabilities())
	store.UseIn(composer)
	ml.UseIn(composer)
	uploadServer, _ := models.Settings("upload_server")
	videoSizeLimitStr, _ := models.Settings("video_size_limit")
	videoSizeLimit, _ := strconv.ParseInt(videoSizeLimitStr, 10, 64)
	log.Println("VideoSizeLimit: ", videoSizeLimit)
	handler, err := tusd.NewHandler(tusd.Config{
		BasePath:      uploadServer + "/account/resupload",
		MaxSize:       videoSizeLimit,
		StoreComposer: composer,
	})
	if err != nil {
		panic(fmt.Errorf("Unable to create handler: %s", err))
	}

	account.Any("/resupload", echo.WrapHandler(http.StripPrefix("/account/resupload", handler.Handler)))
	account.Any("/resupload/*", echo.WrapHandler(http.StripPrefix("/account/resupload/", handler.Handler)))

**Comment by Acconut** [comment]
> I am using the tusd library to upload a file directly to S3 in Go. It seems to be functioning however tusd uploads two files a .info metadata file and a .bin actual content file. only uploading metadata in storage S3. why only upload .info and .bin nothing ?

I am sorry but I don't understand what you are trying to say here. Please rephrase your questions.

Also, please provide all setup details, as the template asked you:
>   Operating System: [e.g. Linux, Windows, macOS]
    Used tusd version: [can be obtained by running tusd -version]
    Used tusd data storage: [e.g. disk store, AWS S3, Google Cloud Storage]
    Used tusd configuration: [what arguments are you using to invoke tusd?]
    Used tus client library: [e.g. tus-js-client, tus-java-client, TUSKit, Uppy.js]

**Comment by arck123** [comment]
Operating System: Linux
Used tusd version: new version
Used tusd data storage: Minio S3
Used tusd configuration: 
Used tus client library: tus-js-client

**Comment by arck123** [comment]
tus-js-client client upload to storage S3 problem, only file .info .. file .bin nothing. i ever upload tus-js-client client upload to storage NFS is successfully .. but problem in storage S3

**Comment by Acconut** [comment]
I am confused. Since tusd 1.0, it does not create any .bin file. So I guess you don't have the latest tusd version, please update.

The binary file now does not have an file ending at all, both when storing on disk as well as when storing on S3. So if you have an upload with the ID `vreueuriehgiurehhiuheriuew`, it will get stored as `vreueuriehgiurehhiuheriuew.info` and ´vreueuriehgiurehhiuheriuew` but not as `vreueuriehgiurehhiuheriuew.bin`.

**Comment by arck123** [comment]
i'm already implementation tusd v1.0.2 from v0.xx
old part my source not work 

this my source:
finishedFile := finisherDataStore.Store.Path + "/" + id + ".bin"
// Get video ID and filename from tusd.FileInfo
fileInfo, err := finisherDataStore.Store.GetInfo(id)

.GetInfo(id) => not working in v1.0.2,  message: filestore has no field or method GetInfo ..
do you have a solution to get metadata tusd.fileinfo ?

thanks

**Comment by Acconut** [comment]
Have a look at this example to see how you can get the FileInfo in tusd 1.0:

https://github.com/tus/tusd/blob/4b7cda81a4d423d5f100bcd97a68384434f8aa86/pkg/handler/unrouted_handler.go#L435-L445

**Comment by arck123** [comment]
GetInfo still not working, this code:

type s3Upload struct {
	id    string
	Store filestore.FileStore
	info *handler.FileInfo
}

func (upload s3Upload) FinishUpload(ctx context.Context) error {
	id := upload.id
	// Get video ID and filename from tusd.FileInfo
	fileInfo, err := upload.GetInfo(ctx) ==>> (type s3upload has no field or method GetInfo)
	if err != nil {
		log.Println("Get FileInfo error:", err)
		return err
	}

Do you have check part my code ?

thanks

**Comment by arck123** [comment]
old part my source not work and mesasge error
./router.go:608:25: undefined: handler.FinisherDataStore
./router.go:611:11: composer.UseFinisher undefined (type *handler.StoreComposer has no field or method UseFinisher)

tusd v0.xxx work this code
tusd v1.xxx not work this code

var finisherDataStore tusd.FinisherDataStore = controllers.FinisherDataStore{
              Store: store,
}
composer.UseFinisher(finisherDataStore)

**Comment by arck123** [comment]
full my code:

		store := filestore.FileStore{
			Path: config.MediaServerPathS3 + "/tus",
		}
		s3Config := &aws.Config{
			Credentials:      credentials.NewStaticCredentials(config.AccessKeyID, config.SecretAccessKey, ""),
			Endpoint:         aws.String(config.BucketName),
			Region:           aws.String(config.Location),
			DisableSSL:       aws.Bool(true),
			S3ForcePathStyle: aws.Bool(true),
		}
		log.Println("s3Config", s3Config)
		ml := s3store.New(config.BucketName, s3.New(session.Must(session.NewSession()), s3Config))
		var finisherDataStore tusd.FinisherDataStore = controllers.FinisherDataStore{
			Store: store,
		}
		composer.UseFinisher(finisherDataStore)
		log.Println(composer.Capabilities())
		store.UseIn(composer)
		ml.UseIn(composer)
		uploadServer, _ := models.Settings("upload_server")
		videoSizeLimitStr, _ := models.Settings("video_size_limit")
		videoSizeLimit, _ := strconv.ParseInt(videoSizeLimitStr, 10, 64)
		log.Println("VideoSizeLimit: ", videoSizeLimit)
		handler, err := tusd.NewHandler(tusd.Config{
			BasePath:      uploadServer + "/account/resupload",
			MaxSize:       videoSizeLimit,
			StoreComposer: composer,
		})

**Comment by arck123** [comment]
implemet tusd v0.xxx nfs/emc work
implement tusd v1.xxx minio S3 not work.

do you have example ?
thanks

**Comment by arck123** [comment]
![sa](https://user-images.githubusercontent.com/18304433/69131008-8fecb300-0a7f-11ea-93ff-12f55720bd4b.png)

only .info upload .. but file video not upload

**Comment by arck123** [comment]
Thanks file has been upload .info and file video

![tes2](https://user-images.githubusercontent.com/18304433/69142841-a998f500-0a95-11ea-96f0-ccec725a9fa6.png)

handler, err := tusd.NewHandler(tusd.Config{
			BasePath:      "/account/resupload",
			//MaxSize:       videoSizeLimit,
			StoreComposer: composer,
})

i deleted it MaxSize in handler and work .. i set max size 1073741824 ..
why only upload .info when i set MaxSize

thanks

**Comment by arck123** [comment]
my old code 
composer.UseFinisher(xx) not work in tusd v1.xx

why not work and what is the function  composer.UseFinisher

thanks

**Comment by Acconut** [comment]
> my old code
composer.UseFinisher(xx) not work in tusd v1.xx

Yes, that's expected. The UseFinisher function does not exist anymore. You should read the release notes for the reasoning behind it: https://github.com/tus/tusd/releases/tag/v1.0.0. TLDR: It's not needed anymore.

> Thanks file has been upload .info and file video .. success

Great to hear! I am going to close this issue then.

**Comment by haimova** [comment]
Hi could you please upload the final code that works for you, I have the same problem
Thanks

**Comment by Neha-Prabhu** [comment]
Hi could you please upload the final code that works for you, I have the same problem
Thanks
